### ISSUE TITLE
Logos sind im Banner nicht rund

### ISSUE THREAD

**Issue by g-voelker** [s4f-dortmund/regionalgruppen_logos#13]
In den Bannern stimmt das Seitenverhältnis der Logos nicht. Das müssen wir fixen.

**Comment by maxnoe** [comment]
LaTeX und zusätzliche Leerzeichen, immer wieder ein Traum

**Comment by maxnoe** [comment]
Neue Dateien hier: https://github.com/s4f-dortmund/regionalgruppen_logos/releases/tag/2021-02-09
