### ISSUE TITLE
Neue Regionalgruppe: Halle

### ISSUE THREAD

**Issue by g-voelker** [s4f-dortmund/regionalgruppen_logos#2]
Ich weiß nicht, wer sonst noch dazu gekommen ist, aber neu ist auf jeden Fall Halle. Siehe:
https://twitter.com/S4F_Halle/status/1175336965023178757

**Comment by maxnoe** [comment]
Ok, wenn ich am Wochenende Zeit finde, werde ich travis beibringen diese logos automatisch zu bauen.

**Comment by maxnoe** [comment]
Wenn's einfach nur ne neue Gruppe ist, ist das File im Webinterface zu bearbeiten sehr einfach

**Comment by g-voelker** [comment]
Eine richtige Pipeline wäre natürlich nice. Ich bin gespannt.

**Comment by maxnoe** [comment]
Haben wir hier: https://github.com/pep-dortmund/corporate-design, sollte also kein allzugroßes Problem sein

**Comment by maxnoe** [comment]
Die Logos werden jetzt automatisch gebaut bei jedem neuen tag
