### ISSUE TITLE
Logo S4F Harz 

### ISSUE THREAD

**Issue by RobinLuge** [s4f-dortmund/regionalgruppen_logos#20]
Hallo zusammen,
ich wollte mal nachfragen, ob es unser S4F Harz Logo schon gibt. Im Release Bereich sind nur log Dateien in der zip...

Liebe Grüße
Robin

**Comment by maxnoe** [comment]
Hi, da ist was schief gegangen, schaue ich mir an

**Comment by maxnoe** [comment]
@RobinLuge Ich habe die Logos nun erstmal manuell hochgeladen, bis ich den automatischen build fixen kann:

https://github.com/s4f-dortmund/regionalgruppen_logos/releases/tag/2022-04-13
