### ISSUE TITLE
Update logos with 2022 data?

### ISSUE THREAD

**Issue by maxnoe** [s4f-dortmund/regionalgruppen_logos#28]
@g-voelker 

In past years, we updated the logo to include latest data. Should we do the same now?

**Comment by g-voelker** [comment]
Hm. Usually a logo would not be updated. I regularly update the warming stripes that I use for Layout purposes but a changing logo with many versions typically  creates problems and confusion over time. My gut feeling say rather not.
What do you think?

**Comment by maxnoe** [comment]
I thought it's pretty nice for this group to have a "living" logo that gets updated as new data is available. Could also be connected with a nice announcment like "last year was again one of the warmest in history".

If you think further than just one or two years, it somewhen becomes strange to only include data until 2020.

Last time we updated the logo in 2021 to include the 2019 and 2020 data.

**Comment by g-voelker** [comment]
Let's do that than. We need to update to HadCrut5, though.

**Comment by g-voelker** [comment]
I have updated the material repository to HadCRUT5 and created a pull request:
https://github.com/s4f-dortmund/material/pull/3

We could thus go forward with the integration into the logo generator - irrespective of the pull request I have created to accomodate the increasing number of groups that need logos.

**Comment by maxnoe** [comment]
Logos are now (once CI passes on main) including stripes until and including 2023
