### ISSUE TITLE
Erstellung_Logos

### ISSUE THREAD

**Issue by PreFra** [s4f-dortmund/regionalgruppen_logos#29]
Hallo ihr Lieben,
kurze Frage zur Erstellung der Logos S4F? Die Fertigen gibt es laut TXT im Release Bereich zum downloaden. Werden die Logos automatisch erstellt und dort abgelegt oder bekommt man diese anderweitig? 
Grüße
Franziska

**Comment by maxnoe** [comment]
Hi,

Ja, die Logos werden wenn ich einen release mache automatisch erstellt und da hochgeladen.

**Comment by PreFra** [comment]
Super, dankeschön!
