### ISSUE TITLE
CI fails with current version of inkscape

### ISSUE THREAD

**Issue by g-voelker** [s4f-dortmund/regionalgruppen_logos#33]
The command line usage of inkscape no longer works. See bug report here:
https://gitlab.com/inkscape/inbox/-/issues/9297

I have the issues both in the CI / action pipeline and offline on my own machine. We can either wai for an upstream fix or consider migrating from inkscape altogether. Any thoughts?

**Comment by g-voelker** [comment]
The reason for the failing CI lies in a bug in gtk3 < 3.25. The issue is fixed upstream but the release isn't in the official repos, yet. Using `ubuntu-latest` as runner for the CI therefore results in the error. For more info check out the upstream bug report:
https://gitlab.com/inkscape/inkscape/-/issues/4177

We may choose another runner for the CI or wait until gtk 3.25 is in the official Ubuntu repos.

**Comment by maxnoe** [comment]
I downgraded inkscape in the CI in #34 to the version that comes with ubuntu 22.04 itself (1.2) and that seems to work
